#! /bin/sh

BASEDIR="$(dirname "$(readlink -f "$0")")"

git pull

echo "Permissions"
echo "kernel.perf_event_paranoid = 2" | sudo tee /etc/sysctl.d/00_perf_event_paranoid.conf

echo "Create Volumes"
sudo mkdir -p /data/frigate/config
sudo mkdir -p /data/frigate/storage

sudo docker volume create \
  --opt type=none \
  --opt o=bind \
  --opt device=/data/frigate/config \
  frigate_config

sudo docker volume create \
  --opt type=none \
  --opt o=bind \
  --opt device=/data/frigate/storage \
  frigate_storage


[ -f "$BASEDIR/config.yml" ] && sudo cp "$BASEDIR/config.yml" /data/frigate/config/config.yml

sudo docker compose down && sudo docker compose up -d --remove-orphans

# UI
sudo firewall-cmd --permanent --add-rich-rule='rule family="ipv4" source address="10.0.0.0/8" port protocol="tcp" port="8971" accept'
sudo firewall-cmd --permanent --add-rich-rule='rule family="ipv4" source address="192.168.0.0/16" port protocol="tcp" port="8971" accept'
sudo firewall-cmd --permanent --add-rich-rule='rule family="ipv4" source address="172.16.0.0/20" port protocol="tcp" port="8971" accept'

# RTSP
sudo firewall-cmd --permanent --add-rich-rule='rule family="ipv4" source address="10.0.0.0/8" port protocol="tcp" port="8554" accept'
sudo firewall-cmd --permanent --add-rich-rule='rule family="ipv4" source address="192.168.0.0/16" port protocol="tcp" port="8554" accept'
sudo firewall-cmd --permanent --add-rich-rule='rule family="ipv4" source address="172.16.0.0/20" port protocol="tcp" port="8554" accept'

# API
sudo firewall-cmd --permanent --add-rich-rule='rule family="ipv4" source address="10.0.0.0/8" port protocol="tcp" port="5000" accept'
sudo firewall-cmd --permanent --add-rich-rule='rule family="ipv4" source address="192.168.0.0/16" port protocol="tcp" port="5000" accept'
sudo firewall-cmd --permanent --add-rich-rule='rule family="ipv4" source address="172.16.0.0/20" port protocol="tcp" port="5000" accept'

sudo firewall-cmd --reload