#! /bin/sh


echo "Create Volumes"
mkdir -p /data/frigate/config
mkdir -p /data/frigate/storate

docker volume create \
  --opt type=none \
  --opt o=bind \
  --opt device=/data/frigate/config \
  frigate_config

docker volume create \
  --opt type=none \
  --opt o=bind \
  --opt device=/data/frigate/storage \
  frigate_storage


cp /data/frigate/config

docker compose up -d --remove-orphans


sudo docker compose up -d --remove-orphans

sudo firewall-cmd --permanent --add-rich-rule='rule family="ipv4" source address="10.0.0.0/8" port protocol="tcp" port="8971" accept'
sudo firewall-cmd --permanent --add-rich-rule='rule family="ipv4" source address="192.168.0.0/16" port protocol="tcp" port="8971" accept'
sudo firewall-cmd --permanent --add-rich-rule='rule family="ipv4" source address="172.16.0.0/20" port protocol="tcp" port="8971" accept'


sudo firewall-cmd --permanent --add-rich-rule='rule family="ipv4" source address="10.0.0.0/8" port protocol="tcp" port="8554" accept'
sudo firewall-cmd --permanent --add-rich-rule='rule family="ipv4" source address="192.168.0.0/16" port protocol="tcp" port="8554" accept'
sudo firewall-cmd --permanent --add-rich-rule='rule family="ipv4" source address="172.16.0.0/20" port protocol="tcp" port="8554" accept'

firewall-cmd --reload